name: "Talking to me"
description: "Get to talk to me!"
title: "[TalkToMe]"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What do you want to say to me?
      description: "Provide anything to say to me."
    validations:
      required: true
