name: Feature Request
title: "[REQ]"
description: Suggest a fflag that should be added
body:
  - type: markdown
    attributes:
      value: |
        ### **Preliminary instructions**
        - is the fflag working?
  - type: textarea
    id: what-happened
    attributes:
      label: What is the fflag and what does it do?
    validations:
      required: true
